### PR TITLE
Update documentation for install

### PR DESCRIPTION
**Pull request by Fantom409**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by schmunk42** [comment]
Actually, it's planned to start with an app template without any assumptions (web,api,cli,....), but it's not ready yet.

But we can link to the project template in the README.

**Comment by samdark** [comment]
There are currently two templates: app, app-api.

**Comment by schmunk42** [comment]
> There are currently two templates: app, app-api.

`app` is actually `app-web`?

**Comment by samdark** [comment]
Well, it's called `app`.

**Comment by schmunk42** [comment]
It's just a question :)

Is it an `app` for everything (web, api, cli, vue, ...)? Or a specific purpose?

**Comment by samdark** [comment]
`app` is a template for classic web + cli.

**Comment by samdark** [comment]
👍

**Pull request merged**
