### PR TITLE
Add sockets extension

### PR DESCRIPTION
**Pull request by dehbka**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | [24](https://github.com/yiisoft/yii-docker/issues/24)

### CODE REVIEW

**Comment by samdark** [comment]
Thanks!

**Comment by schmunk42** [comment]
Was this really be meant to be added to the `min` (minimal) image?

**Comment by samdark** [comment]
It was meant to be added in all images.

**Comment by schmunk42** [comment]
Your decision, but the roadrunner extension seems rather exotic to me.
In comparision, we don't even have MySQL or Postgres PHP extensions on the minimal image.

**Pull request merged**
